type: go

up:
  - go:
      version: 1.23.1
      modules: on
      tools:
        - google.golang.org/protobuf/cmd/protoc-gen-go@latest
        - google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
  - packages:
      - protoc
